{% set name = "asgi-correlation-id" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asgi_correlation_id-{{ version }}.tar.gz
  sha256: 62db23c909a802ce6ec0ac7ceb5f24d03d5358b761b2026c8de5fcbd5424afbd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.7,<4.0
    - starlette >=0.18

test:
  imports:
    - asgi_correlation_id
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snok/asgi-correlation-id
  summary: Middleware correlating project logs to individual requests
  license: BSD-4-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sondrelg
    - ludaavics
